name: Feature request
description: 提出一个新功能或改进建议
title: "[Feature] 简要描述需求"
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 背景/问题
      description: 这个功能解决什么问题？
  - type: textarea
    id: proposal
    attributes:
      label: 方案
      description: 简述你的设想或期望的行为
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你考虑过的其它方案

